In [38]:
import torchvision
import torch
import torch.nn as nn

In [32]:
base_model = torchvision.models.vgg16(pretrained=True)

In [34]:
for layer in base_model.modules():
    print(layer)
    break

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (17): Conv2d

In [16]:
base_model = list(base_model.features)[:-1]
base_model = nn.Sequential(*base_model)
conv1 = nn.Conv2d(512, 512, 1)
dropout1 = nn.Dropout(0.5)

In [17]:
a1=base_model(torch.randn(8,3,224,224))
a1.shape

torch.Size([8, 512, 14, 14])

In [18]:
a2=conv1(a1)
a2.shape

torch.Size([8, 512, 14, 14])

In [19]:
a3=dropout1(a2)
a3.shape

torch.Size([8, 512, 14, 14])

In [20]:
conv2 = nn.Conv2d(512,1024*20,1)

In [21]:
a4=conv2(a3)
a4.shape

torch.Size([8, 20480, 14, 14])

In [22]:
a5=a4.reshape(-1,1024,20,196)
a5.shape

torch.Size([8, 1024, 20, 196])

In [23]:
maxpool=nn.MaxPool2d((20,1))

In [24]:
a6=maxpool(a5)
a6.shape

torch.Size([8, 1024, 1, 196])

In [25]:
a7=a6.reshape(-1,1024,196)
a7.shape

torch.Size([8, 1024, 196])

In [26]:
a8=a7.permute(0,2,1)
a8.shape

torch.Size([8, 196, 1024])

In [27]:
softmax=nn.Softmax(dim=2)

In [28]:
a9=softmax(a8)
a9.shape

torch.Size([8, 196, 1024])

In [29]:
a9[1].shape

torch.Size([196, 1024])

In [30]:
torch.sum(a9[0],dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [72]:
a10=a9.permute(0,2,1).reshape(-1,1024,1,196)
a10.shape

torch.Size([8, 1024, 1, 196])

In [73]:
maxpool2=nn.MaxPool2d((1,196))

In [74]:
a11=maxpool2(a10)
a11.shape

torch.Size([8, 1024, 1, 1])

In [75]:
a12=a11.squeeze()
a12.shape

torch.Size([8, 1024])

In [7]:
d=nn.Dropout(0.5)

In [12]:
aa=torch.randn(5,5)
y=aa**2

In [13]:
d(y)

tensor([[ 0.0000,  0.1276,  1.3079,  0.0000,  0.0000],
        [ 0.0000, 13.4876,  2.0259,  0.0000,  0.0000],
        [ 0.7124,  0.0000,  5.8004,  1.1224,  2.9020],
        [ 1.4645,  0.0811,  0.0000,  1.8155,  0.1056],
        [ 0.0000,  0.0352,  0.0972,  0.2645,  0.0000]])

In [51]:
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import Sequential
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(10, activation='softmax',name='soft'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])



In [52]:
# Generate dummy data
import numpy as np
import keras
data = np.random.random((1000, 100))
labels = np.random.randint(10, size=(1000, 1))

# Convert labels to categorical one-hot encoding
one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)

# Train the model, iterating on the data in batches of 32 samples
model.fit(data, one_hot_labels, epochs=10, batch_size=32)

dense1_layer_model = Model(inputs=model.input,
                                     outputs=model.get_layer('soft').output)
#以这个model的预测值作为输出
dense1_output = dense1_layer_model.predict(data)
 
dense1_output

Epoch 1/10
1000/1000 [==============================] - 1s 625us/step - loss: 2.3834 - acc: 0.1040
Epoch 2/10
1000/1000 [==============================] - 0s 282us/step - loss: 2.3287 - acc: 0.0940
Epoch 3/10
1000/1000 [==============================] - 0s 297us/step - loss: 2.3125 - acc: 0.1020
Epoch 4/10
1000/1000 [==============================] - 0s 296us/step - loss: 2.2997 - acc: 0.1200
Epoch 5/10
1000/1000 [==============================] - 0s 436us/step - loss: 2.2904 - acc: 0.1100
Epoch 6/10
1000/1000 [==============================] - 0s 82us/step - loss: 2.2795 - acc: 0.1180
Epoch 7/10
1000/1000 [==============================] - 0s 82us/step - loss: 2.2717 - acc: 0.1370
Epoch 8/10
1000/1000 [==============================] - 0s 106us/step - loss: 2.2601 - acc: 0.1380
Epoch 9/10
1000/1000 [==============================] - 0s 73us/step - loss: 2.2524 - acc: 0.1500
Epoch 10/10
1000/1000 [==============================] - 0s 71us/step - loss: 2.2414 - acc: 0.1520


array([[0.10994221, 0.10140774, 0.11080837, ..., 0.09173212, 0.10617281,
        0.08699389],
       [0.15377744, 0.08422421, 0.09047195, ..., 0.07036699, 0.1217503 ,
        0.07718779],
       [0.14241292, 0.10160103, 0.09693567, ..., 0.11899488, 0.07380358,
        0.07410032],
       ...,
       [0.09770095, 0.11170392, 0.10249366, ..., 0.1191003 , 0.07754569,
        0.10511004],
       [0.12710132, 0.08330646, 0.07090042, ..., 0.10710155, 0.07563601,
        0.09263028],
       [0.09819156, 0.11862726, 0.09668502, ..., 0.12084874, 0.08523441,
        0.083705  ]], dtype=float32)

In [53]:
a=Out[52]

In [62]:
a.sum(axis=1)

array([0.99999994, 0.99999994, 1.        , 0.99999994, 1.        ,
       1.        , 1.        , 1.        , 0.99999994, 1.        ,
       1.        , 1.        , 0.99999994, 1.        , 0.99999994,
       1.0000001 , 0.99999994, 1.        , 0.9999998 , 0.99999994,
       1.        , 0.99999994, 1.        , 1.        , 0.99999994,
       1.        , 1.        , 0.99999994, 0.99999994, 1.        ,
       0.9999999 , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.9999999 ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99999994, 1.        , 1.        , 1.        , 0.99999994,
       1.        , 0.9999999 , 1.0000001 , 1.        , 1.        ,
       0.99999994, 0.99999994, 1.0000001 , 1.        , 0.99999994,
       1.        , 0.99999994, 0.99999994, 0.99999994, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.9999999 , 1.        , 0.99999994, 1.0000001 , 1.00000

In [39]:
base_model = torchvision.models.vgg16(pretrained=True)
base_model = list(base_model.features)[:-1]
base_model = nn.Sequential(*base_model)

In [43]:
for i,p in enumerate(base_model.named_parameters()):
    print(i,p[1].shape)

0 torch.Size([64, 3, 3, 3])
1 torch.Size([64])
2 torch.Size([64, 64, 3, 3])
3 torch.Size([64])
4 torch.Size([128, 64, 3, 3])
5 torch.Size([128])
6 torch.Size([128, 128, 3, 3])
7 torch.Size([128])
8 torch.Size([256, 128, 3, 3])
9 torch.Size([256])
10 torch.Size([256, 256, 3, 3])
11 torch.Size([256])
12 torch.Size([256, 256, 3, 3])
13 torch.Size([256])
14 torch.Size([512, 256, 3, 3])
15 torch.Size([512])
16 torch.Size([512, 512, 3, 3])
17 torch.Size([512])
18 torch.Size([512, 512, 3, 3])
19 torch.Size([512])
20 torch.Size([512, 512, 3, 3])
21 torch.Size([512])
22 torch.Size([512, 512, 3, 3])
23 torch.Size([512])
24 torch.Size([512, 512, 3, 3])
25 torch.Size([512])


AttributeError: 'ReLU' object has no attribute 'weight'

In [49]:
for p in base_model.parameters():
    p.requires_grad = False
    # If fine-tuning, only fine-tune convolutional blocks 2 through 4

In [51]:
base_model[0].weight.requires_grad

False

In [52]:
list(base_model.children())[-6:]

[Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),
 ReLU(inplace),
 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),
 ReLU(inplace),
 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)),
 ReLU(inplace)]

In [56]:
for c in list(base_model.children())[-6:]:
    print(c)
    for p in c.parameters():
        print(p.shape)
        p.requires_grad = True

Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
torch.Size([512, 512, 3, 3])
torch.Size([512])
ReLU(inplace)
Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
torch.Size([512, 512, 3, 3])
torch.Size([512])
ReLU(inplace)
Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
torch.Size([512, 512, 3, 3])
torch.Size([512])
ReLU(inplace)


In [59]:
list(Out[52][1].parameters())

[]

In [62]:
from collections import OrderedDict
sub_concept_layer = nn.Sequential(OrderedDict([
            ('conv1', nn.Conv2d(512, 512, 1)),
            ('dropout1', nn.Dropout(0.5)), # (-1,512,14,14)
            ('conv2', nn.Conv2d(512, 1600, 1)),
            ('maxpool1', nn.MaxPool2d((80, 1))),  # input need reshape to (-1,L,K,H*W)
            ('softmax1',nn.Softmax(dim = 2)), # reshape input to (-1,L,H*W), # permute(0,2,1)
            ('maxpool2',nn.MaxPool2d((1, 196))) # permute(0,2,1) # reshape to (-1,L,1,H*W)
        ]))

In [68]:
sub_concept_layer.conv1

Conv2d(512, 512, kernel_size=(1, 1), stride=(1, 1))

In [69]:
import torch
import torch.nn as nn
import torchvision
from torchsummary import summary
from collections import OrderedDict
device = torch.device('cuda:1' if torch.cuda.is_available() else 'cpu')


class MIML(nn.Module):

    def __init__(self, L=1024, K=20, batch_size=8, fine_tune=True):
        """
        Arguments:
            L (int):
                number of labels
            K (int):
                number of sub categories
        """
        super(MIML, self).__init__()
        self.L = L
        self.K = K
        self.batch_size = batch_size
        # pretrained ImageNet VGG
        base_model = torchvision.models.vgg16(pretrained=True)
        base_model = list(base_model.features)[:-1]
        self.base_model = nn.Sequential(*base_model)
        self.fine_tune(fine_tune)

        self.sub_concept_layer = nn.Sequential(OrderedDict([
            ('conv1', nn.Conv2d(512, 512, 1)),
            ('dropout1', nn.Dropout(0.5)),  # (-1,512,14,14)
            ('conv2', nn.Conv2d(512, K*L, 1)),
            # input need reshape to (-1,L,K,H*W)
            ('maxpool1', nn.MaxPool2d((K, 1))),
            # reshape input to (-1,L,H*W), # permute(0,2,1)
            ('softmax1', nn.Softmax(dim=2)),
            # permute(0,2,1) # reshape to (-1,L,1,H*W)
            ('maxpool2', nn.MaxPool2d((1, 196)))
        ]))
        # self.conv1 = nn.Conv2d(512, 512, 1))

        # self.dropout1=nn.Dropout(0.5)

        # self.conv2=nn.Conv2d(512, K*L, 1)
        # # input need reshape to (-1,L,K,H*W)
        # self.maxpool1=nn.MaxPool2d((K, 1))
        # # reshape input to (-1,L,H*W)
        # # permute(0,2,1)
        # self.softmax1=nn.Softmax(dim = 2)
        # # permute(0,2,1)
        # # reshape to (-1,L,1,H*W)
        # self.maxpool2=nn.MaxPool2d((1, 196))
        # # squeeze()

    def forward(self, x):
        # IN:(8,3,224,224)-->OUT:(8,512,14,14)
        base_out = self.base_model(x)
        # C,H,W = 512,14,14
        _, C, H, W = base_out.shape
        # OUT:(8,512,14,14)

        conv1_out = self.sub_concept_layer.dropout1(
            self.sub_concept_layer.conv1(base_out))

        # shape -> (n_bags, (L * K), n_instances, 1)
        conv2_out = self.sub_concept_layer.conv2(conv1_out)
        # shape -> (n_bags, L, K, n_instances)
        conv2_out = conv2_out.reshape(-1, self.L, self.K, H*W)
        # shape -> (n_bags, L, 1, n_instances),remove dim: 1
        maxpool1_out = self.sub_concept_layer.maxpool1(conv2_out).squeeze()

        # softmax
        permute1 = maxpool1_out.permute(0, 2, 1)
        softmax1 = self.sub_concept_layer.softmax1(permute1)
        permute2 = softmax1.permute(0, 2, 1)
        # reshape = permute2.unsqueeze(2)
        reshape = permute2.reshape(-1, self.L, 1, H*W)
        # shape -> (n_bags, L, 1, 1)
        maxpool2_out = self.sub_concept_layer.maxpool2(reshape)
        out = maxpool2_out.squeeze()

        return out

    def fine_tune(self, fine_tune=True):
        # only fine_tune the last three convs
        layer = -6
        for p in self.base_model.parameters():
            p.requires_grad = False
        for c in list(self.base_model.children())[-6:]:
            for p in c.parameters():
                p.requires_grad = True