In [14]:
import torchvision
import torch
import torch.nn as nn

In [15]:
base_model = torchvision.models.vgg16(pretrained=True)

In [16]:
base_model = list(base_model.features)[:-1]
base_model = nn.Sequential(*base_model)
conv1 = nn.Conv2d(512, 512, 1)
dropout1 = nn.Dropout(0.5)

In [17]:
a1=base_model(torch.randn(8,3,224,224))
a1.shape

torch.Size([8, 512, 14, 14])

In [18]:
a2=conv1(a1)
a2.shape

torch.Size([8, 512, 14, 14])

In [19]:
a3=dropout1(a2)
a3.shape

torch.Size([8, 512, 14, 14])

In [20]:
conv2 = nn.Conv2d(512,1024*20,1)

In [21]:
a4=conv2(a3)
a4.shape

torch.Size([8, 20480, 14, 14])

In [22]:
a5=a4.reshape(-1,1024,20,196)
a5.shape

torch.Size([8, 1024, 20, 196])

In [23]:
maxpool=nn.MaxPool2d((20,1))

In [24]:
a6=maxpool(a5)
a6.shape

torch.Size([8, 1024, 1, 196])

In [25]:
a7=a6.reshape(-1,1024,196)
a7.shape

torch.Size([8, 1024, 196])

In [26]:
a8=a7.permute(0,2,1)
a8.shape

torch.Size([8, 196, 1024])

In [27]:
softmax=nn.Softmax(dim=2)

In [28]:
a9=softmax(a8)
a9.shape

torch.Size([8, 196, 1024])

In [29]:
a9[1].shape

torch.Size([196, 1024])

In [30]:
torch.sum(a9[0],dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 

In [72]:
a10=a9.permute(0,2,1).reshape(-1,1024,1,196)
a10.shape

torch.Size([8, 1024, 1, 196])

In [73]:
maxpool2=nn.MaxPool2d((1,196))

In [74]:
a11=maxpool2(a10)
a11.shape

torch.Size([8, 1024, 1, 1])

In [75]:
a12=a11.squeeze()
a12.shape

torch.Size([8, 1024])

In [7]:
d=nn.Dropout(0.5)

In [12]:
aa=torch.randn(5,5)
y=aa**2

In [13]:
d(y)

tensor([[ 0.0000,  0.1276,  1.3079,  0.0000,  0.0000],
        [ 0.0000, 13.4876,  2.0259,  0.0000,  0.0000],
        [ 0.7124,  0.0000,  5.8004,  1.1224,  2.9020],
        [ 1.4645,  0.0811,  0.0000,  1.8155,  0.1056],
        [ 0.0000,  0.0352,  0.0972,  0.2645,  0.0000]])

In [51]:
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import Sequential
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(10, activation='softmax',name='soft'))
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])



In [52]:
# Generate dummy data
import numpy as np
import keras
data = np.random.random((1000, 100))
labels = np.random.randint(10, size=(1000, 1))

# Convert labels to categorical one-hot encoding
one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)

# Train the model, iterating on the data in batches of 32 samples
model.fit(data, one_hot_labels, epochs=10, batch_size=32)

dense1_layer_model = Model(inputs=model.input,
                                     outputs=model.get_layer('soft').output)
#以这个model的预测值作为输出
dense1_output = dense1_layer_model.predict(data)
 
dense1_output

Epoch 1/10
1000/1000 [==============================] - 1s 625us/step - loss: 2.3834 - acc: 0.1040
Epoch 2/10
1000/1000 [==============================] - 0s 282us/step - loss: 2.3287 - acc: 0.0940
Epoch 3/10
1000/1000 [==============================] - 0s 297us/step - loss: 2.3125 - acc: 0.1020
Epoch 4/10
1000/1000 [==============================] - 0s 296us/step - loss: 2.2997 - acc: 0.1200
Epoch 5/10
1000/1000 [==============================] - 0s 436us/step - loss: 2.2904 - acc: 0.1100
Epoch 6/10
1000/1000 [==============================] - 0s 82us/step - loss: 2.2795 - acc: 0.1180
Epoch 7/10
1000/1000 [==============================] - 0s 82us/step - loss: 2.2717 - acc: 0.1370
Epoch 8/10
1000/1000 [==============================] - 0s 106us/step - loss: 2.2601 - acc: 0.1380
Epoch 9/10
1000/1000 [==============================] - 0s 73us/step - loss: 2.2524 - acc: 0.1500
Epoch 10/10
1000/1000 [==============================] - 0s 71us/step - loss: 2.2414 - acc: 0.1520


array([[0.10994221, 0.10140774, 0.11080837, ..., 0.09173212, 0.10617281,
        0.08699389],
       [0.15377744, 0.08422421, 0.09047195, ..., 0.07036699, 0.1217503 ,
        0.07718779],
       [0.14241292, 0.10160103, 0.09693567, ..., 0.11899488, 0.07380358,
        0.07410032],
       ...,
       [0.09770095, 0.11170392, 0.10249366, ..., 0.1191003 , 0.07754569,
        0.10511004],
       [0.12710132, 0.08330646, 0.07090042, ..., 0.10710155, 0.07563601,
        0.09263028],
       [0.09819156, 0.11862726, 0.09668502, ..., 0.12084874, 0.08523441,
        0.083705  ]], dtype=float32)

In [53]:
a=Out[52]

In [62]:
a.sum(axis=1)

array([0.99999994, 0.99999994, 1.        , 0.99999994, 1.        ,
       1.        , 1.        , 1.        , 0.99999994, 1.        ,
       1.        , 1.        , 0.99999994, 1.        , 0.99999994,
       1.0000001 , 0.99999994, 1.        , 0.9999998 , 0.99999994,
       1.        , 0.99999994, 1.        , 1.        , 0.99999994,
       1.        , 1.        , 0.99999994, 0.99999994, 1.        ,
       0.9999999 , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.9999999 ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.99999994, 1.        , 1.        , 1.        , 0.99999994,
       1.        , 0.9999999 , 1.0000001 , 1.        , 1.        ,
       0.99999994, 0.99999994, 1.0000001 , 1.        , 0.99999994,
       1.        , 0.99999994, 0.99999994, 0.99999994, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       0.9999999 , 1.        , 0.99999994, 1.0000001 , 1.00000